### ISSUE TITLE
Arc requires T: Sized

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/loom#85] opened 2019-10-23 19:45 UTC
`std::sync::Arc<T>` does not require `T: Sized`, where as loom's version does. This means that code that uses, say, `Arc<dyn Fn>` will not compile with loom, which is unfortunate. I _believe_ we would need to move the `T` to the end of `loom::Arc` for this to work, though that also breaks the layout needed according to `loom::Arc`'s comment:
https://github.com/carllerche/loom/blob/339dd48f57d3b9b786e44db4914d08882d7659bf/src/sync/arc.rs#L11-L17

**Comment by jonhoo** [comment] 2019-10-23 23:44
I believe what is actually needed here is [`CoerceUnsized`](https://doc.rust-lang.org/std/ops/trait.CoerceUnsized.html) which is unstable for the time being ([tracking issue](https://github.com/rust-lang/rust/issues/27732)).

**Comment by carllerche** [comment] 2019-10-24 17:21
Closing as there is no immediate action to take.

**Closed by carllerche** 2019-10-24 17:21 UTC

**Comment by jonhoo** [comment] 2021-09-10 01:42
Not sure — @carllerche would need to chime in there.

**Comment by WaffleLapkin** [comment] 2021-09-10 10:57
Should I make a draft PR?

**Comment by jonhoo** [comment] 2021-09-11 00:09
@WaffleLapkin I think that'd be helpful, and then we can always iterate from there!

**Comment by WaffleLapkin** [comment] 2021-12-06 22:20
For the record: I've created #226 a while ago with the intent to fix it. I think works and even allows a type like `Arc<dyn Read>` to be used. The problem is: without `CoerceUnsized` or something similar it's impossible to actually create `Arc<dyn Read>`.

**Comment by WaffleLapkin** [comment] 2021-12-06 22:22
Though since #226 makes `loom::sync::Arc<T>` basically store `std::sync::Arc<T>`, we could probably add a `from_std` function, so users could coerce the std arc and then create loom arc from it?
